# Generated by Django 5.0.14 on 2026-06-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('prediction', models.CharField(choices=[('spam', 'Spam'), ('ham', 'Ham')], max_length=10)),
                ('confidence', models.FloatField()),
                ('language', models.CharField(default='en', max_length=20)),
                ('security_score', models.IntegerField(default=50)),
                ('fraud_type', models.CharField(blank=True, max_length=50, null=True)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('phishing_analysis', models.JSONField(blank=True, default=dict)),
                ('xai_data', models.JSONField(blank=True, default=dict)),
                ('suspicious_words', models.JSONField(blank=True, default=list)),
                ('urls_found', models.JSONField(blank=True, default=list)),
                ('hasadf_pipeline', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('correct', 'Correct Prediction'), ('wrong', 'Wrong Prediction')], max_length=10)),
                ('corrected_label', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('sms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sms_analysis.smsmessage')),
            ],
            options={
                'db_table': 'feedback',
                'unique_together': {('user', 'sms')},
            },
        ),
    ]
