# Generated by Django 5.0.14 on 2026-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('samples_count', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('model_name', models.CharField(max_length=100)),
                ('included_feedback', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'model_training_logs',
                'ordering': ['-trained_at'],
            },
        ),
    ]
