FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .
COPY ml_models/ /ml_models/

ENV PYTHONUNBUFFERED=1
ENV USE_SQLITE=False

EXPOSE 8000

CMD ["sh", "-c", "python manage.py migrate && python manage.py train_models && gunicorn hsds_project.wsgi:application --bind 0.0.0.0:8000"]
