# Generated by Django 5.0.14 on 2026-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('cluster_keywords', models.JSONField(default=list)),
                ('sample_messages', models.JSONField(default=list)),
                ('affected_users', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('campaign_type', models.CharField(default='spam', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-risk_score', '-detected_at'],
            },
        ),
    ]
